"use client";

import type { ColumnDef } from "@tanstack/react-table";
import { DataTable } from "@/components/shared/data-table";
import { Badge } from "@/components/ui/badge";
import { SCOPE_LABELS } from "@/lib/constants";
import { formatCo2, formatDate, formatNumber } from "@/lib/format";

type Txn = {
  id: string;
  transactionDate: string;
  department: { name: string } | null;
  emissionFactor: { name: string } | null;
  sourceType: string;
  quantity: string | number;
  factorValue: string | number;
  co2eKg: string | number;
  scope: string;
  autoGenerated: boolean;
};

const columns: ColumnDef<Txn>[] = [
  { accessorKey: "transactionDate", header: "Date", cell: ({ row }) => formatDate(row.original.transactionDate) },
  { accessorKey: "department", header: "Department", cell: ({ row }) => row.original.department?.name ?? "—" },
  { accessorKey: "sourceType", header: "Source" },
  { id: "qty", header: "Quantity", cell: ({ row }) => <span className="tabular-nums">{formatNumber(row.original.quantity)}</span> },
  { accessorKey: "factorValue", header: "Factor", cell: ({ row }) => <span className="tabular-nums">{formatNumber(row.original.factorValue, 4)}</span> },
  { accessorKey: "co2eKg", header: "CO₂e", cell: ({ row }) => <span className="font-medium text-env tabular-nums">{formatCo2(row.original.co2eKg)}</span> },
  { accessorKey: "scope", header: "Scope", cell: ({ row }) => <span className="text-sm">{SCOPE_LABELS[row.original.scope] ?? row.original.scope}</span> },
  { accessorKey: "autoGenerated", header: "Origin", cell: ({ row }) => <Badge variant={row.original.autoGenerated ? "success" : "secondary"}>{row.original.autoGenerated ? "Auto" : "Manual"}</Badge> },
];

export function TransactionsClient({ data }: { data: Txn[] }) {
  return <DataTable data={data} columns={columns} searchPlaceholder="Search transactions…" emptyMessage="No carbon transactions yet." pageSize={15} />;
}
