import { prisma } from "@/lib/db";
import { toNumber } from "@/lib/format";
import { getEsgConfig } from "./config.service";
import { logActivity } from "./activityLog.service";
import { HttpError } from "@/lib/api";
import { computeCo2eKg } from "@/lib/esg/calculations";
import type { OperationType, Prisma } from "@prisma/client";

export { computeCo2eKg };

export interface CreateOperationInput {
  organizationId: string;
  departmentId?: string | null;
  operationType: OperationType;
  referenceNumber?: string | null;
  description?: string | null;
  operationDate: Date;
  quantity: number;
  unit: string;
  amount?: number | null;
  emissionFactorId?: string | null;
  metadata?: Prisma.InputJsonValue;
}

/**
 * Create a business operation and, when auto emission calculation is enabled and
 * an emission factor is attached, atomically generate the linked carbon
 * transaction. Returns the operation together with any generated transaction.
 */
export async function createBusinessOperation(
  input: CreateOperationInput,
  actorId: string,
) {
  const config = await getEsgConfig(input.organizationId);

  let factor = null;
  if (input.emissionFactorId) {
    factor = await prisma.emissionFactor.findUnique({
      where: { id: input.emissionFactorId },
    });
    if (!factor || factor.organizationId !== input.organizationId) {
      throw new HttpError(400, "Emission factor not found for this organisation.");
    }
  }

  const shouldAutoCalc = config.autoEmissionCalculationEnabled && !!factor;

  const result = await prisma.$transaction(async (tx) => {
    const operation = await tx.businessOperation.create({
      data: {
        organizationId: input.organizationId,
        departmentId: input.departmentId ?? null,
        operationType: input.operationType,
        referenceNumber: input.referenceNumber ?? null,
        description: input.description ?? null,
        operationDate: input.operationDate,
        quantity: input.quantity,
        unit: input.unit,
        amount: input.amount ?? null,
        emissionFactorId: input.emissionFactorId ?? null,
        metadata: input.metadata,
        createdById: actorId,
      },
    });

    let transaction = null;
    if (shouldAutoCalc && factor) {
      const factorValue = toNumber(factor.factorValue);
      const co2eKg = computeCo2eKg(input.quantity, factorValue);
      transaction = await tx.carbonTransaction.create({
        data: {
          organizationId: input.organizationId,
          departmentId: input.departmentId ?? null,
          businessOperationId: operation.id,
          emissionFactorId: factor.id,
          transactionDate: input.operationDate,
          sourceType: factor.sourceType,
          quantity: input.quantity,
          factorValue,
          co2eKg,
          scope: factor.scope,
          autoGenerated: true,
          calculationDescription: `${input.quantity} ${input.unit} × ${factorValue} ${factor.emissionUnit}/${factor.activityUnit} = ${co2eKg} kgCO₂e`,
          createdById: actorId,
        },
      });
    }

    await logActivity(
      {
        organizationId: input.organizationId,
        userId: actorId,
        action: "operation.create",
        entityType: "BusinessOperation",
        entityId: operation.id,
        newData: {
          operationType: operation.operationType,
          quantity: input.quantity,
          autoGeneratedTransaction: !!transaction,
        },
      },
      tx,
    );

    return { operation, transaction };
  });

  return result;
}

/**
 * Manually (re)generate a carbon transaction for an operation — used when auto
 * calculation is disabled or a factor was attached after the fact.
 */
export async function regenerateCarbonTransaction(operationId: string, actorId: string) {
  const operation = await prisma.businessOperation.findUnique({
    where: { id: operationId },
    include: { emissionFactor: true, carbonTransaction: true },
  });
  if (!operation) throw new HttpError(404, "Operation not found.");
  if (!operation.emissionFactor) {
    throw new HttpError(400, "Attach an emission factor before generating a transaction.");
  }

  const factor = operation.emissionFactor;
  const factorValue = toNumber(factor.factorValue);
  const quantity = toNumber(operation.quantity);
  const co2eKg = computeCo2eKg(quantity, factorValue);

  const data = {
    organizationId: operation.organizationId,
    departmentId: operation.departmentId,
    emissionFactorId: factor.id,
    transactionDate: operation.operationDate,
    sourceType: factor.sourceType,
    quantity,
    factorValue,
    co2eKg,
    scope: factor.scope,
    autoGenerated: false,
    calculationDescription: `${quantity} ${operation.unit} × ${factorValue} ${factor.emissionUnit}/${factor.activityUnit} = ${co2eKg} kgCO₂e`,
    createdById: actorId,
  };

  const transaction = operation.carbonTransaction
    ? await prisma.carbonTransaction.update({
        where: { id: operation.carbonTransaction.id },
        data,
      })
    : await prisma.carbonTransaction.create({
        data: { ...data, businessOperationId: operation.id },
      });

  await logActivity({
    organizationId: operation.organizationId,
    userId: actorId,
    action: "carbon.generate",
    entityType: "CarbonTransaction",
    entityId: transaction.id,
    newData: { co2eKg },
  });

  return transaction;
}
